### ISSUE TITLE
Ojoj :)

### ISSUE THREAD

**Issue by stefangeneralao** [femosc2/geniusify-quiz#1]
https://github.com/femosc2/geniusify-quiz/blob/ddb3fc518291c9990ff5a3492583d7a0d9e12224/node/controllers/authorize.js#L4

**Comment by femosc2** [comment]
Det är bara min mock-backend jag skrev snabbt så att vi skulle ha något att programmera mot, den ska tas bort så fort den riktiga backenden är på plats!
